services:
  web:
    image: nginx:latest
    volumes:
      - app:/var/www
      - storage:/var/www/storage
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
      - web
    depends_on:
      - php
    environment:
      - VIRTUAL_HOST=ventrue.patricksantino.com
      - LETSENCRYPT_HOST=ventrue.patricksantino.com
  php:
    build: 
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - app:/var/www
      - storage:/var/www/storage
    networks:
      - default
      - database
    env_file:
      - .env
  mailhog:
    image: mailhog/mailhog:latest
    networks:
      - default
      - web
    environment:
      - VIRTUAL_HOST=mailhog.patricksantino.com
      - VIRTUAL_PORT=8025
      - LETSENCRYPT_HOST=mailhog.patricksantino.com


volumes:
  app:
  storage:

networks:
  default:
  web:
    name: web
    external: true
  database:
    name: database
    external: true
